project:
  type: website
  output-dir: docs

website:
  title: "Project STRETCH"
  back-to-top-navigation: true
  page-navigation: true
  navbar:
    background: light
  #   # logo: quarto.png
  #   # logo-alt: "Quarto logo."
    collapse-below: lg
    left:
      - href: index.qmd
        text: "Dynamic Thermal Corridor Exploratory Analyses"
      # - href: tmp_page.qmd
      #   text: About
    right:
      - text: "Wildlife Computers Maps"
        menu:
          - text: "2024 Map"
            href: "https://my.wildlifecomputers.com/data/map/?id=66836b103844d032140f0ab6"
            icon: globe
          - text: "2023 Map"
            href: "https://my.wildlifecomputers.com/data/map/?id=646c14fae9b3514a9430a544"
            icon: globe
    
  sidebar:
    pinned: true
    align: center
    style: "docked"
    search: true
    collapse-level: 1
    contents:
      - href: index.qmd
        text: Latest | Date
      - section: hycom_analyses.qmd
        text: Env Analyses
        contents:
          - href: hycom_analyses.qmd
            text: Hycom Analyses
          - href: hycom_vs_oscar.qmd
            text: Hycom vs Oscar
          - href: env_clims.qmd
            text: Climatologies
      # - href: tmp_page.qmd
      #   text: Another Temp Page
      - section: cc_hycom_currents.qmd
        text: Turtle-Env Analyses
        contents:
          - href: cc_hycom_currents.qmd
            text: Turtle-Currents
        
  page-footer:
    # right: "This page is built with ❤️ and [Quarto](https://quarto.org/)."
    left: "&copy; CC-DBriscoe, 2025"

format:
  html:
    theme: 
        light: [cosmo, theme.scss]
        dark: darkly
    code-copy: true
    code-overflow: wrap
    # link-external-icon: true
    link-external-newwindow: true
    link-external-filter: '^(?:http:|https:)\/\/www\.quarto\.org\/custom'
    # css: styles.css
    fontsize: 22px
    toc: true
    toc-location: left
    toc-expand: true	
    number-sections: false
    number-depth: 2
    smooth-scroll: true
    fig-cap-location: top
    scrollable: true

filters:
  # - include-files.lua
  - lightbox
  - quarto
lightbox: 
  match: auto
  effect: zoom
  desc-position: top

