---
title: ""
format: html
engine: knitr
---

<br>
<br>

## Latest additions: 

**15. `{r} "2025-09-02" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [[Updated Figure 6](draft_ms_figs_21Aug2025.qmd#fig-6): Now a 4-panel fig similar to Fig 7 (chl)]{style="font-size: 90%;"}

<br>


**14. `{r} "2025-08-09" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [[Updated MS Figures](draft_ms_figs_21Aug2025.qmd): Updated all ms draft figures. Moved Fig 4 > Fig 2; added SFigs]{style="font-size: 90%;"}

<br>


**13. `{r} "2025-08-09" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [[Updated MS Figures](draft_ms_figs_9Aug2025.qmd): Updated all ms draft figures]{style="font-size: 90%;"}

<br>

**12. `{r} "2025-06-12" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [[Updated Figure 1](draft_ms_figs_12Jun2025.qmd): Added STRETCH tracks]{style="font-size: 90%;"}

- [x]  [[Updated Figures 2, 3, and 8](draft_ms_figs_12Jun2025.qmd#fig-2.-septoct-2006-2007-and-2023-currents-and-turtle-tracks): Removed CCS boundary]{style="font-size: 90%;"}

- [x]  [[Added Draft Figure 6](draft_ms_figs_12Jun2025.qmd#fig-6.-daily-turtle-sst-extractions-n4-2024-cohort): Turtle-SST, Sept-Oct 2024]{style="font-size: 90%;"}

- [x]  [[Updated Draft Fig 7](draft_ms_figs_12Jun2025.qmd#fig-7.-chl-a-and-stretch-turtle-tracks-sept-dec-2024): Turtle-Chla, Sept-Dec 2024]{style="font-size: 90%;"}

- [x]  [[Added Draft SFig 1: Current clim, Sept-Oct 2004-2024:](draft_ms_figs_12Jun2025.qmd#sfig-1.-septoct-currents-2004-2024) Will be used to outline spatial extent of NPC in ENP]{style="font-size: 90%;"}

<br>

**11. `{r} "2025-05-14" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Reorganized [Figure Order to Match Draft MS Outline](draft_ms_figs_14May2025.qmd)]{style="font-size: 90%;"}

- [x]  [[Added Draft Fig 8: Sept-Oct 2014:](draft_ms_figs_14May2025.qmd#fig-8.-septoct-currents-2014) left out of previous version]{style="font-size: 90%;"}

<br>

**10. `{r} "2025-04-22" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [[Reorganized Draft Figure Order](draft_ms_figs_22Apr2025.qmd) from previous version]{style="font-size: 90%;"}

- [x]  [Updated [Draft Figure 1:](draft_ms_figs_22Apr2025.qmd#fig-1.-map-of-north-pacific-loggerhead-tracks) Map of NP Turtle Tracks]{style="font-size: 90%;"}

- [x]  [[Reordered Draft Figures 2-5:](draft_ms_figs_22Apr2025.qmd#fig-2.-septoct-currents-and-historic-turtle-tracks-2006---2007) Same figures, different order ]{style="font-size: 90%;"}

- [x]  [Added [Draft Figure 6:](draft_ms_figs_22Apr2025.qmd#fig-6.-stretch-turtle-swimming-vs-current-speeds-4-indivs-2024) Weekly U, V current vs swimming speeds (4 CC Turtles in 2024)]{style="font-size: 90%;"}

- [x]  [Added [Draft SFigure:](draft_ms_figs_22Apr2025.qmd#sfig-x.-stretch-turtle-swimming-vs-current-with-vectors-4-indivs-2024) Weekly U, V current vs swimming with vectors (4 CC Turtles in 2024)]{style="font-size: 90%;"}


<br>


**9. `{r} "2025-04-11" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Updated [Draft Figure 1:](draft_ms_figs_10Apr2025.qmd#fig-1.-septoct-currents-and-historic-turtle-tracks-2006---2007) Currents, 18°C Isotherm, & Turtles (includes Sept & Oct 2006 & 2007)]{style="font-size: 90%;"}

- [x]  [Updated [Draft Figure 3:](draft_ms_figs_10Apr2025.qmd#fig-3.-comparison-of-septoct-2014-2024-currents-isotherm) Currents, 18°C Isotherm, & 4 CC Turtles (includes Sept & Oct  2014 vs 2014)]{style="font-size: 90%;"}

- [x]  [Updated [Individual Historic Turtle Tracks (2006 - 2007) plots](cc_hycom_currents.qmd#october) (includes Sept & Oct Zonal Average 2006 & 2007)]{style="font-size: 90%;"}


<br>

**8. `{r} "2025-04-10" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Updated [Draft Figure 1:](draft_ms_figs_10Apr2025.qmd#fig-1.-enp-september-currents-and-historic-turtle-tracks-2006---2007) Currents, 18°C Isotherm, & Turtles (Sept 2006 & 2007)]{style="font-size: 90%;"}

- [x]  [Added [Draft Figure 3:](draft_ms_figs_10Apr2025.qmd#fig-3.-comparison-of-septoct-2014-2024-currents-isotherm) Currents, 18°C Isotherm, & 4 CC Turtles (Sept 2014 vs 2014)]{style="font-size: 90%;"}

- [x]  [Updated [Individual Historic Turtle Tracks (2006 - 2007) for Sept Zonal Average (2006 & 2007 only)](cc_hycom_currents.qmd#september) plots]{style="font-size: 90%;"}

- [x]  [Added [Turtle-Hycom-Copernicus Histogram Comparisons](cc_hycom_currents.qmd#cohort-histograms-u-v) (1993 - 2024)]{style="font-size: 90%;"}

<br>

**7. `{r} "2025-04-03" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Added Draft Figure 1: [Currents, 18°C Isotherm, & Turtles Climatology (2014-2024)](draft_ms_figs_1Apr2025.qmd)]{style="font-size: 90%;"}
- [x]  [Added Draft Figure 2: [Avg Turtle Lat by Year Group](draft_ms_figs_1Apr2025.qmd#fig-2.-mean-turtle-latitude-by-year-group) from Briscoe et al. (2025) FMS paper]{style="font-size: 90%;"}
- [x]  [Added Draft Figure 4: [4 Cohort 2 Turtles in CC & Chl-a (Sept/Oct 2024)](draft_ms_figs_1Apr2025.qmd#fig-4.-four-cohort-2-turtles-in-cc-chl-a-septoct-2024)]{style="font-size: 90%;"}
<br>

- [x]  [Added [Sept/Oct Currents Climatologies (2014 - 2024): 1°, 2°, 5° spatial grids ](env_clims.qmd#currents-sept---oct-2014---2024-1-panel) plots]{style="font-size: 90%;"}
- [x]  [Added Monthly [Sept/Oct SST + 18°C Isotherm (2014 - 2024)](env_clims.qmd#sst-sept---oct-2014---2024)) plots]{style="font-size: 90%;"}
- [x]  [Added [Individual Historic Turtle Tracks (2005 - 2008) & Sept/Oct Zonal Clim (2014 - 2024)](cc_hycom_currents.qmd#cohort-2-tracks-in-enp-by-individual) plots]{style="font-size: 90%;"}


<br>

**6. `{r} "2025-03-31" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Added [Turtle Tracks in ENP by Group](cc_analyses.qmd#turtle-tracks-in-enp-by-group): Historic, STRETCH Cohorts 1 & 2]{style="font-size: 90%;"}


<br>

**5. `{r} "2025-02-27" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Added Monthly Mean [Turtle Latitude plots](cc_analyses.qmd)]{style="font-size: 90%;"}
- [x]  [Added Map of [CCS vs CCLME spatial boundaries](cc_analyses.qmd#ccs-vs-cclme-extent)]{style="font-size: 90%;"}
- [x]  [Added Turtle Movements [into CCS plots](cc_analyses.qmd#turtle-ccs-movements)]{style="font-size: 90%;"}
- [x]  [Added Turtle-Hycom [Hovmoller plots](cc_hovm.qmd#turtle-hycom-hovm)]{style="font-size: 90%;"}
- [x]  [Added Turtle-SST [Hovmoller plots](cc_hovm.qmd#turtle-sst-hovm)]{style="font-size: 90%;"}
- [x]  [Added Map of Monthly Turtle-Hycom [Sept-Oct plots](cc_hycom_currents.qmd#individual-tracks-u-v)]{style="font-size: 90%;"}

<br>

**4. `{r} "2025-02-20" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Added Hycom [Hovmoller plots](hycom_analyses.qmd)]{style="font-size: 90%;"}

<br>

**3. `{r} "2025-02-13" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Added Turtle-Hycom [Histograms](cc_hycom_currents.qmd#cohort-histograms-u-v-1) (1993 - 2024)]{style="font-size: 90%;"}


<br>

**2. `{r} "2025-02-06" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Added Hycom vs Oscar Product [Comparisons](hycom_vs_oscar.qmd) (1993 - 2024)]{style="font-size: 90%;"}


<br>

**1. `{r} "2025-01-25" |> as.Date() |> format("%b-%d-%Y")`:**

- [x]  [Added SST & Salinity [Climatologies](env_clims.qmd#sst-salinity-all-months-1993---2024) (1993 - 2024)]{style="font-size: 90%;"}


